version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Webpublico
    ports:
      - "5432:5432"
    volumes:
      - ./webpublico_banco:/var/lib/postgresql/data